# Generated by Django 5.0.6 on 2024-06-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id_produk', models.AutoField(primary_key=True, serialize=False)),
                ('id_kategori', models.IntegerField()),
                ('nama_produk', models.CharField(max_length=100)),
                ('harga_produk', models.IntegerField()),
                ('berat_produk', models.IntegerField()),
                ('foto_produk', models.CharField(max_length=100)),
                ('deskripsi_produk', models.TextField()),
                ('stok_produk', models.IntegerField()),
            ],
            options={
                'db_table': 'produk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdukFoto',
            fields=[
                ('id_produk_foto', models.AutoField(primary_key=True, serialize=False)),
                ('id_produk', models.IntegerField()),
                ('nama_produk_foto', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'produk_foto',
                'managed': False,
            },
        ),
    ]
