# Generated by Django 5.0.6 on 2024-06-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(blank=True, db_column='Kode', max_length=50, null=True)),
                ('warna', models.CharField(blank=True, db_column='Warna', max_length=50, null=True)),
                ('merk', models.CharField(blank=True, db_column='Merk', max_length=50, null=True)),
                ('ketersediaan', models.CharField(blank=True, db_column='Ketersediaan', max_length=50, null=True)),
                ('jadwal', models.CharField(blank=True, db_column='Jadwal', max_length=50, null=True)),
                ('notifikasi', models.BooleanField(blank=True, db_column='Notifikasi', null=True)),
                ('foto_produk', models.ImageField(blank=True, db_column='Foto Produk', null=True, upload_to='')),
            ],
            options={
                'db_table': 'produk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdukFoto',
            fields=[
                ('id_produk_foto', models.AutoField(primary_key=True, serialize=False)),
                ('nama_produk_foto', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'produk_foto',
                'managed': False,
            },
        ),
    ]
