# Generated by Django 5.0.6 on 2024-06-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id_pembayaran', models.AutoField(primary_key=True, serialize=False)),
                ('id_pembelian', models.IntegerField()),
                ('nama', models.CharField(max_length=255)),
                ('bank', models.CharField(max_length=255)),
                ('jumlah', models.IntegerField()),
                ('tanggal', models.DateField()),
                ('bukti', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pembayaran',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('id_pembelian', models.AutoField(primary_key=True, serialize=False)),
                ('id_pelanggan', models.IntegerField()),
                ('tanggal_pembelian', models.DateField()),
                ('total_pembelian', models.IntegerField()),
                ('alamat_pengiriman', models.TextField()),
                ('status_pembelian', models.CharField(max_length=100)),
                ('resi_pengiriman', models.CharField(max_length=50)),
                ('totalberat', models.IntegerField()),
                ('provinsi', models.CharField(max_length=255)),
                ('distrik', models.CharField(max_length=255)),
                ('tipe', models.CharField(max_length=255)),
                ('kodepos', models.CharField(max_length=255)),
                ('ekspedisi', models.CharField(max_length=255)),
                ('paket', models.CharField(max_length=255)),
                ('ongkir', models.IntegerField()),
                ('estimasi', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pembelian',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PembelianProduk',
            fields=[
                ('id_pembelian_produk', models.AutoField(primary_key=True, serialize=False)),
                ('id_pembelian', models.IntegerField()),
                ('id_produk', models.IntegerField()),
                ('jumlah', models.IntegerField()),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.IntegerField()),
                ('berat', models.IntegerField()),
                ('subberat', models.IntegerField()),
                ('subharga', models.IntegerField()),
            ],
            options={
                'db_table': 'pembelian_produk',
                'managed': False,
            },
        ),
    ]
