# Generated by Django 5.0.6 on 2024-06-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('nama_lengkap', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id_pelanggan', models.AutoField(primary_key=True, serialize=False)),
                ('email_pelanggan', models.CharField(max_length=100)),
                ('password_pelanggan', models.CharField(max_length=50)),
                ('nama_pelanggan', models.CharField(max_length=100)),
                ('telepon_pelanggan', models.CharField(max_length=100)),
                ('alamat_pelanggan', models.TextField()),
            ],
            options={
                'db_table': 'pelanggan',
                'managed': False,
            },
        ),
    ]
