# Generated by Django 5.0.6 on 2024-06-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kategori', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'kategori',
                'managed': False,
            },
        ),
    ]
