# Generated by Django 5.0.6 on 2024-06-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jenis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(blank=True, db_column='Kode', max_length=50, null=True)),
                ('jenis', models.CharField(blank=True, db_column='Jenis', max_length=50, null=True)),
                ('berat', models.CharField(blank=True, db_column='Berat', max_length=50, null=True)),
                ('kapasitas', models.CharField(blank=True, db_column='Kapasitas', max_length=50, null=True)),
                ('daya_mesin', models.CharField(blank=True, db_column='Daya Mesin', max_length=50, null=True)),
            ],
            options={
                'db_table': 'jenis',
                'managed': False,
            },
        ),
    ]
